### ISSUE TITLE
createMicrophoneClient throwing UnsatisfiedLinkError

### ISSUE THREAD

**Issue by terrykwon** [Azure-Samples/Cognitive-Speech-STT-Android#19]
```
01-16 21:05:24.546 14476-14476/com.terrykwon.pronoucethis E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.terrykwon.pronoucethis, PID: 14476
01-16 21:05:24.546 14476-14476/com.terrykwon.pronoucethis E/AndroidRuntime: java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/com.terrykwon.pronoucethis/files/instant-run/dex/slice-uk.co.chrisjenx-calligraphy-2.2.0_92d7df936d8b43d9c68181e123968e73efed0b15-classes.dex", dex file "/data/data/com.terrykwon.pronoucethis/files/instant-run/dex/slice-support-annotations-25.1.0_c4e73635696c0f9be0d2d8c2b0cb80fc45dc8c20-classes.dex", dex file "/data/data/com.terrykwon.pronoucethis/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.terrykwon.pronoucethis/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.terrykwon.pronoucethis/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.terrykwon.pronoucethis/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.terrykwon.pronoucethis/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.terrykwon.pronoucethis/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.terrykwon.pronoucethis/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.terrykwon.pronoucethis/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.terrykwon.pronoucethis/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.terrykwon.pronoucethis/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.terrykwon.pronoucethis/files/instant-run/dex/slice-realm-annotations-2.2.2_02d9e4ab60db00b82608bcdf5078170ff0f89476-classes.dex", dex file "/data/data/com.terrykwon.pronoucethis/files/instant-run/dex/slice-io.realm-realm-android-library-2.2.2_cc0748f99dceb83d2db97030a01124a72853bb04-classes.dex", dex file "/data/data/com.terrykwon.pronoucethis/files/instant-run/dex/slice-io.realm-android-adapters-1.4.0_831d5aa17e183ac96906f1bf9639199febe9691f-classes.dex", dex file "/data/data/com.terrykwon.pronoucethis/files/instant-run/dex/slice-com.microsoft.projectoxford-speechrecognition-1.1.0_8d6e5f57e891e8fba2efbe501c78ee640c04b145-classes.dex", dex file "/data/data/com.terrykwon.pronoucethis/files/instant-run/dex/slice-com.getkeepsafe.relinker-relinker-1.2.2_50e0f1518039b7904336f1961538bf14d92a3106-classes.dex", dex file "/data/data/com.terrykwon.pronoucethis/files/instant-run/dex/slice-com.android.support-transition-25.1.0_ecd044d4a8e5c3b06ce472ff64998982ab71e40b-classes.dex", dex file "/data/data/com.terrykwon.pronoucethis/files/instant-run/dex/slice-com.android.support-support-vector-drawable-25.1.0_af070fd2fb0387c4eb7bcadd001bf5379f5af5fa-classes.dex", dex file "/data/data/com.terrykwon.pronoucethis/files/instant-run/dex/slice-com.android.support-support-v4-25.1.0_95078cc348966858c3676914b4f4ae3aa1f38318-classes.dex", dex file "/data/data/com.terrykwon.pronoucethis/files/instant-run/dex/slice-com.android.support-support-media-compat-25.1.0_dfd071f8968cbc980b3b5c6b3d2a399cb2c67374-classes.dex", dex file "/data/data/com.terrykwon.pronoucethis/files/instant-run/dex/slice-com.android.support-support-fragment-25.1.0_86d6168cf94eced3b71db9b34ea643b49465bc88-classes.dex", dex file "/data/data/com.terrykwon.pronoucethis/files/instant-run/dex/slice-com.android.support-support-core-utils-25.1.0_2bf796308c3a6dc0f78c84076d7e598c5d3d81db-classes.dex", dex file "/data/data/com.terrykwon.pronoucethis/files/instant-run/dex/slice-com.android.support-support-core-ui-25.1.0_d3af3773db0bde4977712683e7bea7568638849d-classes.dex", dex file "/data/data/com.terrykwon.pronoucethis/files/instant-run/dex/slice-com.android.support-support-compat-25.1.0_68cf8eab2ec0ad2dd371538e09acec2540b6bb08-classes.dex", dex file "/data/data/com.terrykwon.pronoucethis/files/instant-run/dex/slice-com.android.support-recyclerview-v7-25.1.0_a414585025cbafeab5b3232cb13ffdfb235f0260-classes.dex", dex file "/data/data/com.terrykwon.pronoucethis/files/instant-run/dex/slice-com.android.support-percent-25.1.0_16f402a1d342bc82c7b25960f7bf4a1476701c30-classes.dex", dex file "/data/data/c
01-16 21:05:24.547 14476-14476/com.terrykwon.pronoucethis E/AndroidRuntime: om.terrykwon.pronoucethis/files/instant-run/dex/slice-com.android.support-design-25.1.0_d94e1649b864d688582b004d9e4455f8f5a2cf13-classes.dex", dex file "/data/data/com.terrykwon.pronoucethis/files/instant-run/dex/slice-com.android.support-appcompat-v7-25.1.0_8f75defda2754ffd4cec4ec0c5f8c0c12af2b336-classes.dex", dex file "/data/data/com.terrykwon.pronoucethis/files/instant-run/dex/slice-com.android.support-animated-vector-drawable-25.1.0_1901c3115ed16cc1ce797d8ea94c371195f5eaf7-classes.dex", dex file "/data/data/com.terrykwon.pronoucethis/files/instant-run/dex/slice-SpeechSDK_6d7faa4ce7621e2379c015a0366dcea2929628a3-classes.dex"],nativeLibraryDirectories=[/data/app/com.terrykwon.pronoucethis-2/lib/arm64, /data/app/com.terrykwon.pronoucethis-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libandroid_platform.so"
                                                                                at java.lang.Runtime.loadLibrary0(Runtime.java:984)
                                                                                at java.lang.System.loadLibrary(System.java:1530)
                                                                                at com.microsoft.bing.speech.Conversation.<clinit>(Conversation.java:68)
                                                                                at com.microsoft.cognitiveservices.speechrecognition.SpeechRecognitionServiceFactory.createMicrophoneClient(SpeechRecognitionServiceFactory.java:747)
                                                                                at com.terrykwon.pronouncethis.main.MainPresenter.initializeMicClient(MainPresenter.java:34)
                                                                                at com.terrykwon.pronouncethis.main.MainActivity.onCreate(MainActivity.java:80)
                                                                                at android.app.Activity.performCreate(Activity.java:6679)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                                at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

Everything was working perfectly until I added a library (Realm) to my app. Theoretically, Realm shouldn't conflict with Cognitive Services; I experimented with disabling any link between the two, yet the error still persists. Maybe it has to do with loading too many libraries? However, I also tried calling `createMicrophoneClient` manually, not through the Activity lifecycle callbacks, but that didn't change anything.

**Comment by priyaravi20** [comment]
We are not aware of an conflicts here.

**Comment by Mun1z** [comment]
I have the same error =/
