### ISSUE TITLE
AndroidSDK for Speech fails on

### ISSUE THREAD

**Issue by aixiaolinzi** [Azure-Samples/Cognitive-Speech-STT-Android#4]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.microsoft.AzureIntelligentServicesExample-1/base.apk"],nativeLibraryDirectories=[/data/app/com.microsoft.AzureIntelligentServicesExample-1/lib/arm64, /data/app/com.microsoft.AzureIntelligentServicesExample-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libandroid_platform.so"
上面是我遇到的问题，就是 我的工程中需要的.so文件有64位的。
![qq 20160720144155](https://cloud.githubusercontent.com/assets/13093507/16977365/29d083c8-4e88-11e6-807a-381d0187a4fc.png)
但是你们提供的只有32位的。怎么解决？？在Demo中，我的手机是可以运行的但是导入自己的工程就不可以了。
在Demo中的build.gradle有这么一段
productFlavors {
        x86 {
            ndk {
                abiFilter "x86"
            }
        }
        arm {
            ndk {
                abiFilters "armeabi"
            }
        }
    }
但是我在自己的build.gradle中添加以上代码，内有任何效果。。

**Comment by kabirkhan** [comment]
I ran into a similar problem today. You shouldn't alter your build.gradle file by adding the product flavors. This is unnecessary. 

Android Studio looks for .so files in the folder named jniLibs by default. Create the folder jniLibs inside of app > src > main. You should include your .so file in a subfolder of jniLibs depending on the product flavor.

Your folder structure should look something like this and you can remove what you added to the build.gradle file.

|--app: 
|--|--src: 
|--|--|--main 
|--|--|--|--jniLibs 
|--|--|--|--|--armeabi 
|--|--|--|--|--|--libandroid_platform.so
|--|--|--|--|--x86 
|--|--|--|--|--|--libandroid_platform.so

**Comment by amitks2015** [comment]
@kabirkhan I am also facing similar issue, but removing productFlavours from build.gradle doesn't help. I see exactly same error as above.
But when add productFlavours I get a different error.

> java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.knowles.bali-1/lib/arm/libandroid_platform.so" has bad ELF magic
                                                                    at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                    at java.lang.System.loadLibrary(System.java:1076)
                                                                    at com.microsoft.bing.speech.Conversation.<clinit>(Conversation.java:68)
                                                                    at com.microsoft.cognitiveservices.speechrecognition.SpeechRecognitionServiceFactory.createDataClient(SpeechRecognitionServiceFactory.java:147)

Any help is appreciated.

**Comment by kabirkhan** [comment]
Try updating your project to SDK version 23 or higher. Also make sure you are using the newest version of gradle and that you have downloaded the libandroid_platform.so files directly from this repo. If it still doesn't work, attach a screenshot of your project structure so I can take a look.

**Comment by amitks2015** [comment]
I am using latest tools.
   minSdkVersion 19
   targetSdkVersion 24
  com.android.tools.build:gradle:2.1.3

Please take a look at the project structure. Circled directories already exist in my project and contain few other .so files.

![bing](https://cloud.githubusercontent.com/assets/13938746/18539942/a8aa340a-7b38-11e6-9f4f-3b68258175f0.png)

Getting below error.
> com.knowles.bali E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.knowles.bali, PID: 11002
                                                                  java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.knowles.bali-1/base.apk"],nativeLibraryDirectories=[/data/app/com.knowles.bali-1/lib/arm, /data/app/com.knowles.bali-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libandroid_platform.so"
                                                                      at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                      at java.lang.System.loadLibrary(System.java:1076)
                                                                      at com.microsoft.bing.speech.Conversation.<clinit>(Conversation.java:68)
                                                                      at com.microsoft.cognitiveservices.speechrecognition.SpeechRecognitionServiceFactory.createDataClient(SpeechRecognitionServiceFactory.java:147)

**Comment by amitks2015** [comment]
Gradle file:
> apply plugin: 'com.android.application'

android {

    signingConfigs {
        config {
           ..........................
           ..........................
        }
    }
    compileSdkVersion 24
    buildToolsVersion "24.0.0"
    packagingOptions {
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/LICENSE.txt'
    }

    defaultConfig {
        applicationId "com.knowles.bali"
        minSdkVersion 19
        targetSdkVersion 24
        versionCode 227
        versionName "2.2.7"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.config
        }
        debug {
        }
    }
}

allprojects {
    repositories {
        jcenter()
        flatDir {
            dirs 'libs'
        }
    }
}

dependencies {
   ..................................................
   .....................................................
    compile 'com.microsoft.projectoxford:speechrecognition:1.1.0'
}

**Comment by amitks2015** [comment]
crash is gone when I renamed existing armeabi-v7a to armeabi. But, still no success with the text result from a pre recorded wav file. 
Any idea about this issue.
https://github.com/Microsoft/Cognitive-Speech-STT-Android/issues/11

**Comment by aixiaolinzi** [comment]
谢谢各位，已经解决问题。就是在armeabi-v7a中放入.......so文件。。
这个适配问题好像华为手机明显。。

**Comment by priyaravi20** [comment]
Closing due to inactivity.
